# Generated by Django 5.0.14 on 2026-07-07 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'topic',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('api_endpoint', models.URLField(max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VPS',
                'verbose_name_plural': 'VPS',
                'db_table': 'vps',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TikTokProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=255)),
                ('daily_video_limit', models.IntegerField(default=5)),
                ('videos_today', models.IntegerField(default=0)),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_profiles', to='core.topic')),
                ('vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_profiles', to='core.vps')),
            ],
            options={
                'verbose_name': 'TikTok Profile',
                'verbose_name_plural': 'TikTok Profiles',
                'db_table': 'tiktok_profile',
                'ordering': ['profile_name'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(help_text='YouTube Channel ID (e.g. UCxxxxx)', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('channel_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, help_text='Admin assigns topic after channel creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_channels', to='core.topic')),
            ],
            options={
                'verbose_name': 'YouTube Channel',
                'verbose_name_plural': 'YouTube Channels',
                'db_table': 'youtube_channel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(help_text='YouTube Video ID', max_length=255, unique=True)),
                ('video_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_to_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.tiktokprofile')),
                ('youtube_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.youtubechannel')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'video',
                'ordering': ['-created_at'],
            },
        ),
    ]
