# Generated by Django 5.0.14 on 2026-07-07 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_usage_count', models.IntegerField(default=0)),
                ('daily_usage_limit', models.IntegerField(default=1400)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gemini API Key',
                'verbose_name_plural': 'Gemini API Keys',
                'db_table': 'gemini_api_key',
                'ordering': ['last_used_at'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='is_split_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='parent_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_parts', to='core.video'),
        ),
        migrations.AddField(
            model_name='video',
            name='part_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('splitting', 'Splitting'), ('split', 'Split'), ('processing', 'Processing'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
