# Generated by Django 5.1.15 on 2026-07-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='bypass_cooldown',
            field=models.BooleanField(default=False, verbose_name='Bỏ qua thời gian chờ (cooldown)'),
        ),
    ]
