# Generated by Django 5.0.14 on 2026-07-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_topic_bypass_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokprofile',
            name='is_beta',
            field=models.BooleanField(default=False),
        ),
    ]
